dataset:
  root_dir: "./data/"
  annotation_file: "./data/annotations.json"

train:
  batch_size: 10
  num_epochs: 10
  learning_rate: 0.001
  images: "./data/"
  annotations: "./data/annotations.json"

val:
  batch_size: 10
  images: "./data/"
  annotations: "./data/annotations.json"

model:
  name: "fasterrcnn_resnet50_fpn"
  pretrained: true

output_dir: "./models/trained_models/"
