dataset_original:
  root_dir: ./data
  images: ./data/images
  annotation_file: ./data/annotation_5class.json

dataset:
  root_dir: ./dataset
  dataset: ./dataset/dataset.yaml

train:
  root_dir: ./dataset/train
  batch_size: 10
  num_epochs: 10
  learning_rate: 0.001
  images: ./dataset/images/train
  labels: ./dataset/labels/train

val:
  root_dir: ./dataset/test
  batch_size: 10
  images: ./dataset/images/test
  labels: ./dataset/labels/test

model:
  name: ./models/yolov8n.pt
  pretrained: true
  num_classes: num_classes = 5
output_dir: ./models/trained_models/