dataset_original:
  root_dir: ./data
  images: ./data/images
  annotation_file: ./data/annotation_5class.json

dataset:
  root_dir: ./dataset
  dataset: ./dataset/dataset.yaml

train:
  root_dir: ./dataset/train
  images: ./dataset/images/train
  labels: ./dataset/labels/train

model:
  name: ./models/yolov8n.pt

model_best:
  name: ./models/best.pt
output_dir: ./models/trained_models/